let Employees=[{"id":1,"Name":"Anni","gender":"Female"},
    {"id":2,"Name":"Catarina","gender":"Female"},
    {"id":3,"Name":"Rhodie","gender":"Female"},
    {"id":4,"Name":"Ad","gender":"Male"},
    {"id":5,"Name":"Myrwyn","gender":"Male"},
    {"id":6,"Name":"Dael","gender":"Female"},
    {"id":7,"Name":"Putnem","gender":"Male"},
    {"id":8,"Name":"Piper","gender":"Female"},
    {"id":9,"Name":"Berri","gender":"Female"},
    {"id":10,"Name":"Haydon","gender":"Male"},
    {"id":11,"Name":"Mabel","gender":"Female"},
    {"id":12,"Name":"Evanne","gender":"Polygender"},
    {"id":13,"Name":"Stafford","gender":"Male"},
    {"id":14,"Name":"Tedd","gender":"Male"},
    {"id":15,"Name":"Felizio","gender":"Male"},
    {"id":16,"Name":"Lainey","gender":"Female"},
    {"id":17,"Name":"Winfield","gender":"Male"},
    {"id":18,"Name":"Starla","gender":"Female"},
    {"id":19,"Name":"Michele","gender":"Male"},
    {"id":20,"Name":"Gabrielle","gender":"Female"},
    {"id":21,"Name":"Ola","gender":"Female"},
    {"id":22,"Name":"David","gender":"Male"},
    {"id":23,"Name":"Rosaline","gender":"Female"},
    {"id":24,"Name":"Odelinda","gender":"Bigender"},
    {"id":25,"Name":"Evelin","gender":"Male"},
    {"id":26,"Name":"Maximilien","gender":"Male"},
    {"id":27,"Name":"Angus","gender":"Male"},
    {"id":28,"Name":"Lynsey","gender":"Female"},
    {"id":29,"Name":"Maurise","gender":"Male"},
    {"id":30,"Name":"Merill","gender":"Male"},
    {"id":31,"Name":"Alphard","gender":"Male"},
    {"id":32,"Name":"Gladys","gender":"Female"},
    {"id":33,"Name":"Asa","gender":"Male"},
    {"id":34,"Name":"Bennett","gender":"Male"},
    {"id":35,"Name":"Oran","gender":"Male"},
    {"id":36,"Name":"Berkie","gender":"Male"},
    {"id":37,"Name":"Brunhilda","gender":"Female"},
    {"id":38,"Name":"Madelon","gender":"Female"},
    {"id":39,"Name":"Candida","gender":"Female"},
    {"id":40,"Name":"Karlens","gender":"Bigender"},
    {"id":41,"Name":"Valry","gender":"Female"},
    {"id":42,"Name":"Nicola","gender":"Male"},
    {"id":43,"Name":"Brady","gender":"Male"},
    {"id":44,"Name":"Janetta","gender":"Female"},
    {"id":45,"Name":"Faulkner","gender":"Male"},
    {"id":46,"Name":"Milissent","gender":"Female"},
    {"id":47,"Name":"Sabina","gender":"Female"},
    {"id":48,"Name":"Hartley","gender":"Genderfluid"},
    {"id":49,"Name":"Natal","gender":"Male"},
    {"id":50,"Name":"Lissy","gender":"Female"},
    {"id":51,"Name":"Alejandrina","gender":"Non-binary"},
    {"id":52,"Name":"Babbie","gender":"Female"},
    {"id":53,"Name":"Neilla","gender":"Female"},
    {"id":54,"Name":"Marie-ann","gender":"Bigender"},
    {"id":55,"Name":"Shawnee","gender":"Female"},
    {"id":56,"Name":"Panchito","gender":"Male"},
    {"id":57,"Name":"Selena","gender":"Female"},
    {"id":58,"Name":"Abby","gender":"Female"},
    {"id":59,"Name":"Nanine","gender":"Female"},
    {"id":60,"Name":"Eudora","gender":"Female"},
    {"id":61,"Name":"Morgan","gender":"Female"},
    {"id":62,"Name":"Fayina","gender":"Female"},
    {"id":63,"Name":"Stanfield","gender":"Male"},
    {"id":64,"Name":"Koren","gender":"Female"},
    {"id":65,"Name":"Siusan","gender":"Genderqueer"},
    {"id":66,"Name":"Barnaby","gender":"Male"},
    {"id":67,"Name":"Opaline","gender":"Female"},
    {"id":68,"Name":"Gisella","gender":"Female"},
    {"id":69,"Name":"Christophe","gender":"Male"},
    {"id":70,"Name":"Torie","gender":"Female"},
    {"id":71,"Name":"Hernando","gender":"Male"},
    {"id":72,"Name":"Corbet","gender":"Male"},
    {"id":73,"Name":"Putnem","gender":"Male"},
    {"id":74,"Name":"Petey","gender":"Male"},
    {"id":75,"Name":"Flory","gender":"Genderqueer"},
    {"id":76,"Name":"Livvie","gender":"Female"},
    {"id":77,"Name":"Jarad","gender":"Male"},
    {"id":78,"Name":"Blair","gender":"Female"},
    {"id":79,"Name":"Renee","gender":"Female"},
    {"id":80,"Name":"Cate","gender":"Female"},
    {"id":81,"Name":"Harland","gender":"Male"},
    {"id":82,"Name":"Beryle","gender":"Female"},
    {"id":83,"Name":"Michale","gender":"Male"},
    {"id":84,"Name":"Hollis","gender":"Male"},
    {"id":85,"Name":"Paulina","gender":"Female"},
    {"id":86,"Name":"Herman","gender":"Male"},
    {"id":87,"Name":"Mariel","gender":"Female"},
    {"id":88,"Name":"Ellerey","gender":"Male"},
    {"id":89,"Name":"Alvis","gender":"Male"},
    {"id":90,"Name":"Lucky","gender":"Female"},
    {"id":91,"Name":"Nerta","gender":"Female"},
    {"id":92,"Name":"Suzi","gender":"Female"},
    {"id":93,"Name":"Manfred","gender":"Male"},
    {"id":94,"Name":"Rebecca","gender":"Female"},
    {"id":95,"Name":"Flss","gender":"Female"},
    {"id":96,"Name":"Chickie","gender":"Male"},
    {"id":97,"Name":"Benni","gender":"Female"},
    {"id":98,"Name":"Tuckie","gender":"Male"},
    {"id":99,"Name":"Curry","gender":"Male"},
    {"id":100,"Name":"Bayard","gender":"Male"}]

    let female=Employees.filter((emp)=>{
        return emp.gender==="Female"

    })
     let male=Employees.filter((emp)=>{
        return emp.gender==="Male"

    })

    // for(emp of Employees){
    //     if(emp.gender=="Female"){
    //         female.push(emp)
    //     }else{
    //         male.push(emp)

    //     }
    // }
    console.log(female.length);
    console.log(male.length);